In [8]:
import numpy as np

### 第一題
原來b會跟著連動

In [31]:
a = [1,2,3]
b = a
a.append(4)
print(b)

[1, 2, 3, 4]


### 第二題～第五題

In [32]:
t = (23,'abc',4.56,(2,3),'def')

In [33]:
t[1:4]

('abc', 4.56, (2, 3))

In [34]:
t[1:-1]

('abc', 4.56, (2, 3))

In [35]:
t[:2]

(23, 'abc')

In [36]:
t[2:]

(4.56, (2, 3), 'def')

### 第六題

In [37]:
np.arange(10,30,5)

array([10, 15, 20, 25])

### 第七題

In [39]:
a = np.arange(10)**3
a[:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

### 第八題

In [40]:
x_data = np.linspace(-1,1,300)[:,np.newaxis] #將矩陣(300)換成(300,1)
x_data.shape

(300, 1)

### 第九題

In [43]:
(1,2,3)+(4,5,6)

(1, 2, 3, 4, 5, 6)

### 第十題

In [42]:
a = np.array([[1,1],[0,1]])
b = np.array([[2,0],[3,4]])
a*b

array([[2, 0],
       [0, 4]])